sudo: false
language: go
go_import_path: shanhu.io/misc

go:
    - "1.11"

install:
    - go get ./...
    - go get shanhu.io/tools/cmd/smlchk
    - go get github.com/golang/lint/golint

script:
    - test -z `gofmt -s -l .`
    - go test ./...
    - smlchk -path="shanhu.io/misc"
    - golint ./...
    - go vet ./...
